"""Add wallets, admin flag, and video task models

Revision ID: 2400f32b4530
Revises: 13f886ad94a0
Create Date: 2026-05-22 10:33:46.716989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2400f32b4530'
down_revision: Union[str, Sequence[str], None] = '13f886ad94a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('reward_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_tasks_id'), 'video_tasks', ['id'], unique=False)
    op.create_table('user_video_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_task_id'], ['video_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_video_tasks_id'), 'user_video_tasks', ['id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deposit_wallet_balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('withdrawal_wallet_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'withdrawal_wallet_balance')
    op.drop_column('users', 'deposit_wallet_balance')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_user_video_tasks_id'), table_name='user_video_tasks')
    op.drop_table('user_video_tasks')
    op.drop_index(op.f('ix_video_tasks_id'), table_name='video_tasks')
    op.drop_table('video_tasks')
    # ### end Alembic commands ###
